apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wechat-webhook-ems
  name: wechat-webhook-ems
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wechat-webhook-ems
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wechat-webhook-ems
    spec:
      containers:
        - command:
            - sh
            - -c
            - /data/wechat-webhook/start.sh 77d13fe6-0047-48bc-803d-904b24590892 :8888
          image: 'registry.cn-hangzhou.aliyuncs.com/novacloud/wechat-webhook-new:ems'
          imagePullPolicy: IfNotPresent
          name: wechat-webhook-ems
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: GRAFANA_URL
              value: "http://grafana:3000"
            - name: ALERT_DOMAIN
              value: "alertmanager"
            - name: DEFAULT_ROBOT
              value: "your-default-robot-key"
            - name: KONG_API_ENDPOINT
              value: "https://8.136.109.47"
            - name: KONG_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kong-api-secret
                  key: token
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

